sfos: Allow D-Bus activation only through systemd
sailfishos/bluez5 pull request #2
Opened 2021-08-18 01:33 UTC by spiiroin

[sailfish] Allow D-Bus activation only through systemd. JB#52572

Starting D-Bus services should happen only via systemd. Using a dummy
Exec line in D-Bus configuration ensures that systemd can't be bypassed.

Signed-off-by: Simo Piiroinen <simo.piiroinen@jolla.com>

2021-08-18 02:08 UTC, Thaodan requested changes
Please just drop the sed on the dbus service file, the upstream version of this file already uses /bin/false.

2021-08-19 05:04 UTC, spiiroin commented
> upstream version of this file already uses /bin/false

Did not spot that myself, but so it seems.

2021-08-19 06:10 UTC, jusa approved these changes

2021-08-19 09:44 UTC, Thaodan approved these changes

2021-08-19 13:37 UTC, jusa requested changes
Hmh only checked the full commit message now, could you remove the tag [sailfish] from the commit? Or change to just "sailfish:"

2021-08-20 05:17 UTC, jusa approved these changes

2021-08-20 05:17 UTC, merged

2021-08-20 05:19 UTC, jusa commented
> Hmh only checked the full commit message now, could you remove the tag [sailfish] from the commit? Or change to just "sailfish:"

Amended commit myself.